services:
  # ------------------------ DB ------------------------
  db:
    image: postgres:16-alpine
    container_name: festival_prod_db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data_prod:/var/lib/postgresql/data
      - ./backend/db/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./backend/db/02_import_reference.sql:/docker-entrypoint-initdb.d/02_import_reference.sql
      - ./backend/db/03_data_demo.sql:/docker-entrypoint-initdb.d/03_data_demo.sql
    networks:
      - app_net

  # --------------------- Backend ----------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: festival_prod_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    volumes:
      - ./certs:/app/certs:ro
    # Pas de "ports" ici : le backend n'est accessible QUE via Nginx (sécurité)
    networks:
      - app_net

  # -------------------- Frontend ----------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: festival_prod_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"    # HTTP (Redirige vers HTTPS)
      - "443:443"  # HTTPS
    volumes:
      - ./certs:/etc/nginx/certs:ro
    networks:
      - app_net

  # --------------------- Adminer ----------------------
  adminer:
    image: adminer:latest
    container_name: festival_prod_adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080" # Accessible sur http://162.38.111.43:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - app_net

# --------------------- Volumes/Network ----------------
volumes:
  db_data_prod:

networks:
  app_net:
